# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20170928_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200)),
                ('descripciondeltrabajo', models.CharField(max_length=200)),
                ('cargahoraria', models.CharField(max_length=200)),
                ('profesion', models.CharField(max_length=200)),
            ],
        ),
    ]
