# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_ofertas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertas',
            old_name='cargahoraria',
            new_name='horarios',
        ),
        migrations.RenameField(
            model_name='ofertas',
            old_name='descripciondeltrabajo',
            new_name='trabajo',
        ),
    ]
