# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20170928_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Desocupado',
        ),
    ]
