# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eliminarusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EliminarUsuario',
        ),
    ]
