# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171109_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferta',
            name='profesion',
            field=models.CharField(max_length=200),
        ),
    ]
